stages:
  - build

build-job:
  stage: build
  image: openusm:latest
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_DEPTH: 1
    GIT_STRATEGY: fetch
  script:
    - echo "Compiling the code..."
    - pwd
    - apt-get update
    - apt-get install -y --no-install-recommends git ca-certificates cmake make mingw-w64
    - rm -rf /var/cache/apt
    - update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
    - cmake -B build
    - cd build
    - make -j4
    - echo "Compile complete."
